function closeDiv(){$("#close-message").fadeTo("slow",0.01,function(){$(this).slideUp("slow",function(){$(this).hide()})})}window.setTimeout("closeDiv();",2500);
$('a[href*=#]').click(function(){if(location.pathname.replace(/^\//,'')==this.pathname.replace(/^\//,'')&&location.hostname==this.hostname){var $target=$(this.hash);$target=$target.length&&$target||$('[name='+this.hash.slice(1)+']');if($target.length){var targetOffset=$target.offset().top;$('html,body').animate({scrollTop:targetOffset},1000);return false;}}});$('.forumbutton,.button').bind({mousedown:function(){$(this).addClass('mousedown');},blur:function(){$(this).removeClass('mousedown');},mouseup:function(){$(this).removeClass('mousedown');}});$('.forum_thread_user_post input[type="checkbox"]').bind('click',function(e){var $this=$(this);if($this.is(':checked')){$this.parents('tr:first').addClass('checked');$this.parents('tr:first').next('tr').addClass('checked');$this.parents('tr:first').prev('tr').addClass('checked');}else{$this.parents('tr:first').removeClass('checked');$this.parents('tr:first').next('tr').removeClass('checked');$this.parents('tr:first').prev('tr').removeClass('checked');}});$('.forum_table input[type="checkbox"]').bind('click',function(e){var $this=$(this);if($this.is(':checked')){$this.parents('tr:first').addClass('checked');}else{$this.parents('tr:first').removeClass('checked');}});$('.dropselect').styleddropdown();$("#s").val("Search...").css("color","#A0A0A0").focus(function(){$(this).css("color","black");if($(this).val()=="Search..."){$(this).val("");}}).blur(function(){$(this).css("color","#A0A0A0");if($(this).val()==""){$(this).val("Search...");}});$('#testimonials blockquote').quovolver();$('#slidwshow').anythingSlider({width:600,height:350,buildArrows:false,resizeContents:false,buildNavigation:false,toggleControls:false,delay:5000,autoPlay:true});
var lang = {
	"SA":"Find support in <a href=\"http://www.phpfusion-ar.com\" target=\"_blank\" rel=\"nofollow\">PHP-Fusion Arabia</a>",
	"BE":"Find support in <a href=\"http://www.phpfusion-nederlands.info\" target=\"_blank\" rel=\"nofollow\">PHP-Fusion Belgium</a>",
	"BR":"Find support in <a href=\"http://www.phpfusion-br.com\" target=\"_blank\" rel=\"nofollow\">PHP-Fusion Brazil</a>",
	"DK":"Find support in <a href=\"http://www.php-fusion.dk\" target=\"_blank\" rel=\"nofollow\">PHP-Fusion Denmark</a>",
	"CZ":"Find support in <a href=\"http://www.phpfusion.cz\" target=\"_blank\" rel=\"nofollow\">PHP-Fusion Czech Republic</a>",
	"FR":"Find support in <a href=\"http://www.phpfusion-fr.com\" target=\"_blank\" rel=\"nofollow\">PHP-Fusion France</a>",
	"DE":"Find support in <a href=\"http://www.phpfusion-support.de\" target=\"_blank\" rel=\"nofollow\">PHP-Fusion Germany</a>",
	"HU":"Find support in <a href=\"http://www.php-fusion.co.hu\" target=\"_blank\" rel=\"nofollow\">PHP-Fusion Hungary</a>",
	"IR":"Find support in <a href=\"http://www.fusion.alaviweb.com\" target=\"_blank\" rel=\"nofollow\">PHP-Fusion Iran</a>",
	"IT":"Find support in <a href=\"http://www.php-fusion.it\" target=\"_blank\" rel=\"nofollow\">PHP-Fusion Italy</a>",
	"NL":"Find support in <a href=\"http://www.phpfusion-nederlands.info\" target=\"_blank\" rel=\"nofollow\">PHP-Fusion Netherlands</a>",
	"NO":"Find support in <a href=\"http://www.phpfusion-no.com\" target=\"_blank\" rel=\"nofollow\">PHP-Fusion Norway</a>",
	"PL":"Find support in <a href=\"http://www.php-fusion.pl\" target=\"_blank\" rel=\"nofollow\">PHP-Fusion Poland</a>",
	"RO":"Find support in <a href=\"http://www.phpfusion.ro\" target=\"_blank\" rel=\"nofollow\">PHP-Fusion Romania</a>",
	"RU":"Find support in <a href=\"http://netck.ru\" target=\"_blank\" rel=\"nofollow\">PHP-Fusion Russia</a>",
	"RS":"Find support in <a href=\"http://www.yu-fusion.org\" target=\"_blank\" rel=\"nofollow\">PHP-Fusion Serbia</a>",
	"ES":"Find support in <a href=\"http://php-fusion.uni.cc\" target=\"_blank\" rel=\"nofollow\">PHP-Fusion Spain</a>",
	"SE":"Find support in <a href=\"http://www.php-fusion.se\" target=\"_blank\" rel=\"nofollow\">PHP-Fusion Sweden</a>",
	"TR":"<a href=\"http://www.phpfusionturkiye.com\" target=\"_blank\">PHP-Fusion Türkiye</a> destek sitesinden Türkçe destek alabilirsiniz.",
	"DF":"<a href=\"http://www.php-fusion.co.uk/viewpage.php?page_id=39\">PHP-Fusion International Network</a>"
}
$.getJSON("http://api.wipmania.com/jsonp?callback=?",function(data){var elem=$("#profile")
switch(data.address.country_code){case"SA":elem.append(lang.SA);break;case"BE":elem.append(lang.BE);break;case"BR":elem.append(lang.BR);break;case"DK":elem.append(lang.DK);break;case"CZ":elem.append(lang.CZ);break;case"FR":elem.append(lang.FR);break;case"DE":elem.append(lang.DE);break;case"HU":elem.append(lang.HU);break;case"IR":elem.append(lang.IR);break;case"DE":elem.append(lang.DE);break;case"IT":elem.append(lang.IT);break;case"NL":elem.append(lang.NL);break;case"NO":elem.append(lang.NO);break;case"PL":elem.append(lang.PL);break;case"RO":elem.append(lang.RO);break;case"RU":elem.append(lang.RU);break;case"RS":elem.append(lang.RS);break;case"ES":elem.append(lang.ES);break;case"SE":elem.append(lang.SE);break;case"TR":elem.append(lang.TR);break;default:elem.append(lang.DF);break;}});$('.spoiler_click').click(function(){if($(this).next().is(':hidden')){$(this).next().slideDown('normal');}else{$(this).next().slideUp('normal');}});$('a.slide_click').click().toggle(function(){$('.spoiler_click').next().slideDown('normal');return false;},function(){$('.spoiler_click').next().slideUp('normal');return false;});$('a.slide_down').click(function(){$('.spoiler_click').next().slideDown('normal');return false;});$('a.slide_up').click(function(){$('.spoiler_click').next().slideUp('normal');return false;});